services:
  - type: web
    name: ase-naki-mongodb
    runtime: docker
    plan: free
    branch: mongodb-crud-docker
    healthCheckPath: /actuator/health
    envVars:
      - key: MONGODB_URI
        sync: false
