spring.application.name=Azizul
spring.mongodb.uri=${MONGODB_URI}
server.port=${PORT:8080}
server.address=0.0.0.0
spring.thymeleaf.cache=false
spring.data.mongodb.auto-index-creation=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
